const List<String> interestsConstants = [
  '🍃 Nature',
  '🏝 Travel',
  '✍🏻 Writing',
  '🙂 People',
  '💪 Gym & Fitness',
  '🗣 Language',
  '📸 Photography',
  '🎤 Karaoke',
  '‍🧘🏻‍♂️ Yoga',
  '️🏊🏻‍♀️ Swimming',
  '⛰️ ️Traveling',
  '🧱 Crafting',
  '🎶 Music',
  '🎻 Instrumentals',
  '🚴🏻‍ Cycling',
  '🎮 Video Games',
  '📖 Reading',
  '🏀 Sports',
  '🎣 Fishing',
  '🥾 Hiking',
  '🧶 Knitting',
  '🏋🏼‍♀ Fitness'
      '🏈 Football',
];

final Map<String, String> interestMap = {
  'Nature': '🍃 Nature',
  'Travel': '🏝 Travel',
  'Writing': '✍🏻 Writing',
  'People': '🙂 People',
  'Gym & Fitness': '💪 Gym & Fitness',
  'Language': '🗣 Language',
  'Photography': '📸 Photography',
  'Karaoke': '🎤 Karaoke',
  'Yoga': '🧘🏻‍♂️ Yoga',
  'Swimming': '🏊🏻‍♀️ Swimming',
  'Traveling': '⛰️ Traveling',
  'Crafting': '🧱 Crafting',
  'Music': '🎶 Music',
  'Instrumentals': '🎻 Instrumentals',
  'Cycling': '🚴🏻‍ Cycling',
  'Video Games': '🎮 Video Games',
  'Reading': '📖 Reading',
  'Sports': '🏀 Sports',
  'Fishing': '🎣 Fishing',
  'Hiking': '🥾 Hiking',
  'Knitting': '🧶 Knitting',
  'Fitness': '🏋🏼‍♀ Fitness',
  'Football': '🏈 Football',
};
